BUILD_DIR := bin
TARGET := $(BUILD_DIR)/load_test
CC ?= gcc
CFLAGS ?= -std=c99 -Wall -Wextra -Wpedantic -Iheader
CONFIG_FOLDER ?= config/

.PHONY: all build run clean

all: build

build:
	@echo "build demo load dengan gcc..."
	@mkdir -p $(BUILD_DIR)
	@$(CC) $(CFLAGS) src/load.c demo_load/demo_load.c -o $(TARGET)
	@echo "build selesai: $(TARGET)"

run: build
	./$(TARGET) $(CONFIG_FOLDER)

clean:
	rm -f $(TARGET)